const bios = [
    "Dreamer, Community Volunteer, Ninja in Training, Choco-holic, Han Solo's College Roommate. I probably still live in my mom's basement. ",
    "Community Volunteer, Curator, Genomic Computational Biologist, Creator of Systems, Tape therapist. I was really tired yesterday. ",
    "The first thing people usually notice about me is my bold personality, closly followed by my smashing thighs. I hope you will find my thighs to be as special as new born kittens, and my eyelashes as awesome as the first moon landing.",
    "I work as a doctor, helping consumers. This allows me to exercise my skills: saving lives and programming computers. My idol is Will Smith. When I'm struggling with my job, I think of Will Smith and feel inspired to continue. I once saw Will Smith at a petrol station, so I feel we have a deep connection - almost spiritual, like the mist on an autumn day, or similar.",
    "I work as a author, helping students. This allows me to exercise my skills: bravery and kindness. One day, I was just about to stop work when Michael Palin appeared from nowhere and congratulated me on a job well done. Of course, now, Michael Palin and me are best friends. A lesser woman would get a big head.",
    "burn that excel spread sheet",
    "My greatest pain in life is that I will never be able to see myself perform life.",
    "An 'extremely credible source' has called my office and told me that Barack Obama's birth certificate is a fraud",
    "I hate when I'm on a flight and I wake up with a water bottle next to me like oh great now I gotta be responsible for this water bottle",
    "I’m nice at ping pong",
    "I leave my emojis bart Simpson color",
    "I’ll say things that are serious and put them in a joke form so people can enjoy them. We laugh to keep from crying.",
    "I'm a creative genius",
    "Editor, Fan, Professional Troublemaker, Fantasy Fruit Loop, Vampire Slayer.",
    "In 2009 I was short selling weed whackers for the government.",
    "I feel like I'm too busy writing history to read it.",
    "If I don’t scream, if I don’t say something then no one’s going to say anything.",
    "For me, money is not my definition of success. Inspiring people is a definition of success",
    "I think I do myself a disservice by comparing myself to Steve Jobs and Walt Disney and human beings that we’ve seen before. It should be more like Willy Wonka…and welcome to my chocolate factory.",
    "I'm the best",
    "Tweeting is legal and also therapeutic",
    "Sometimes I push the door close button on people running towards the elevator. I just need my own elevator sometimes. My sanctuary.",
    "I make awesome decisions in bike stores!!!",
    "You can’t look at a glass half full or empty if it’s overflowing.",
    "Fur pillows are hard to actually sleep on",
    "My life goals include: 1) Meet Eric Idle, 2) Punish men for being evil, 3) Discover that there are still some good men in the world, 4) Become the best housekeeper I can be, 5) Help all the viewers in the world",
    "My last partner nailed my grandmother to a spike. Now I'm looking for a bold man with short fingernails, as I read in a magazine that they are the least evil.",
    "The first thing people usually notice about me is my delightful personality, closly followed by my smashing fingers. I hope you will not laugh at my fingers, as men have in the past, or treat my hands like a joke.",
    "I'm just a humble person trying to make my way in the world. I cannot imagine why you'd want to date little old me, but if an ordinary, nice person is something you think you could find yourself growing to love, I do have all my own teeth and an adequate pension plan.",
    "If you're the right one for me, you'll be special and funny. You won't be afraid to meet my parents and will have a healthy respect for perfection.",
    "Let me tell you about a funny thing that happened to me last week. I was just helping an elderly across the road when I was hit by a car. I needed three stitches. BOOM!",
    "Food maven. Hardcore web geek. Pop culture fanatic. Subtly charming creator. Proud tv advocate.",
    "Writer. Award-winning music advocate. Entrepreneur. Hipster-friendly bacon nerd. Proud twitter lover. Total web junkie.",
    'Did you ever hear the tragedy of Darth Plagueis The Wise? I thought not. It’s not a story the Jedi would tell you. It’s a Sith legend.',
    'Darth Plagueis was a Dark Lord of the Sith, so powerful and so wise he could use the Force to influence the midichlorians to create life… He had such a knowledge of the dark side that he could even keep the ones he cared about from dying.',
    'The dark side of the Force is a pathway to many abilities some consider to be unnatural. He became so powerful… the only thing he was afraid of was losing his power, which eventually, of course, he did.',
    'Unfortunately, he taught his apprentice everything he knew, then his apprentice killed him in his sleep. Ironic. He could save others from death, but not himself.',
    'I Am Not A Human And I Don't Speak English',
    'How can mirrors be real if our eyes aren’t real.',
    'The only way to change something is to shock it. If you want your muscles to grow, you have to shock them. If you want society to change, you have to shock them.'
];
export default bios;
